[Chore] Update Sqlite Async Web
powersync-ja/powersync.dart pull request #118
Opened 2024-07-04 14:24 UTC by stevensJourney

# Overview

This updates the `sqlite_async` package to `0.8.0` which now contains web support.

2024-07-04 15:20 UTC, mugikhan requested changes

2024-07-04 15:20 UTC, mugikhan commented on demos/supabase-todolist/pubspec.yaml
I think we should also update all the demos to pin the version of powersync to `powersync: 1.3.0-alpha.7`

2024-07-04 15:27 UTC, mugikhan approved these changes

2024-07-04 15:28 UTC, stevensJourney commented on demos/supabase-todolist/pubspec.yaml
Fair enough. I've pinned those now. For context the `powersync_attachments_helper`'s version was pinned to avoid the Pana package downgrade test from failing, but it can't hurt to pin the demos.

2024-07-04 15:45 UTC, merged

2024-08-13 08:29 UTC, rkistner commented
Pana checks fail on version bumps - safe to ignore.